import { ProductTier } from "@/types/subscriptions";

export const CREDIT_PACKS: ProductTier[] = [
  {
    name: "Mini",
    id: "mini",
    productId: process.env.NEXT_PUBLIC_CREEM_MINI_PRODUCT_ID ?? "",
    price: "$5",
    priceValue: 5,
    billingPeriod: "one_time",
    plan: "free",
    description: "Try a single song creation.",
    creditAmount: 1,
    songRetentionDays: 30,
    priorityGeneration: false,
    reportCreditsIncluded: false,
    featured: false,
  },
  {
    name: "Standard",
    id: "standard",
    productId: process.env.NEXT_PUBLIC_CREEM_STANDARD_PRODUCT_ID ?? "",
    price: "$12",
    priceValue: 12,
    billingPeriod: "one_time",
    plan: "free",
    description: "Create multiple songs at a better rate.",
    creditAmount: 3,
    songRetentionDays: 30,
    priorityGeneration: false,
    reportCreditsIncluded: false,
    featured: true,
  },
  {
    name: "Pro Pack",
    id: "pro_pack",
    productId: process.env.NEXT_PUBLIC_CREEM_PRO_PACK_PRODUCT_ID ?? "",
    price: "$25",
    priceValue: 25,
    billingPeriod: "one_time",
    plan: "free",
    description: "Best value for serious creators.",
    creditAmount: 7,
    songRetentionDays: 30,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
];

export const SUBSCRIPTION_TIERS: ProductTier[] = [
  {
    name: "Basic Monthly",
    id: "basic_monthly",
    productId: process.env.NEXT_PUBLIC_CREEM_BASIC_MONTHLY_PRODUCT_ID ?? "",
    price: "$9/mo",
    priceValue: 9,
    billingPeriod: "monthly",
    plan: "basic",
    description: "For regular creators who want songs that last.",
    creditAmount: 3,
    songRetentionDays: null,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
  {
    name: "Pro Monthly",
    id: "pro_monthly",
    productId: process.env.NEXT_PUBLIC_CREEM_PRO_MONTHLY_PRODUCT_ID ?? "",
    price: "$19/mo",
    priceValue: 19,
    billingPeriod: "monthly",
    plan: "pro",
    description: "Priority generation and maximum creative output.",
    creditAmount: 8,
    songRetentionDays: null,
    priorityGeneration: true,
    reportCreditsIncluded: true,
    featured: true,
  },
  {
    name: "Basic Yearly",
    id: "basic_yearly",
    productId: process.env.NEXT_PUBLIC_CREEM_BASIC_YEARLY_PRODUCT_ID ?? "",
    price: "$79/yr",
    priceValue: 79,
    billingPeriod: "yearly",
    plan: "basic",
    description: "Save 27% with annual billing.",
    creditAmount: 36,
    songRetentionDays: null,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
  {
    name: "Pro Yearly",
    id: "pro_yearly",
    productId: process.env.NEXT_PUBLIC_CREEM_PRO_YEARLY_PRODUCT_ID ?? "",
    price: "$169/yr",
    priceValue: 169,
    billingPeriod: "yearly",
    plan: "pro",
    description: "Best value for dedicated creators. Save 26%.",
    creditAmount: 96,
    songRetentionDays: null,
    priorityGeneration: true,
    reportCreditsIncluded: true,
    featured: true,
  },
];

export const ALL_TIERS = [...CREDIT_PACKS, ...SUBSCRIPTION_TIERS];

export function getTierById(id: string): ProductTier | undefined {
  return ALL_TIERS.find((tier) => tier.id === id);
}
