import { ProductTier } from "@/types/subscriptions";

export const CREDIT_PACKS: ProductTier[] = [
  {
    name: "Starter Pack",
    id: "standard",
    productId: process.env.CREEM_STANDARD_PRODUCT_ID ?? "",
    price: "$9",
    priceValue: 9,
    billingPeriod: "one_time",
    plan: "free",
    description: "Best for quick creation bursts.",
    creditAmount: 1600,
    songRetentionDays: 30,
    priorityGeneration: false,
    reportCreditsIncluded: false,
    featured: true,
  },
  {
    name: "Pro Pack",
    id: "pro_pack",
    productId: process.env.CREEM_PRO_PACK_PRODUCT_ID ?? "",
    price: "$19",
    priceValue: 19,
    billingPeriod: "one_time",
    plan: "free",
    description: "High-volume pack for frequent creation.",
    creditAmount: 5000,
    songRetentionDays: 30,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
];

export const SUBSCRIPTION_TIERS: ProductTier[] = [
  {
    name: "Basic Monthly",
    id: "basic_monthly",
    productId: process.env.CREEM_BASIC_MONTHLY_PRODUCT_ID ?? "",
    price: "$8.99/mo",
    priceValue: 8.99,
    billingPeriod: "monthly",
    plan: "basic",
    description: "For regular creators who want songs that last.",
    creditAmount: 3000,
    songRetentionDays: null,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
  {
    name: "Pro Monthly",
    id: "pro_monthly",
    productId: process.env.CREEM_PRO_MONTHLY_PRODUCT_ID ?? "",
    price: "$18.99/mo",
    priceValue: 18.99,
    billingPeriod: "monthly",
    plan: "pro",
    description: "Priority generation and maximum creative output.",
    creditAmount: 10000,
    songRetentionDays: null,
    priorityGeneration: true,
    reportCreditsIncluded: true,
    featured: true,
  },
  {
    name: "Basic Yearly",
    id: "basic_yearly",
    productId: process.env.CREEM_BASIC_YEARLY_PRODUCT_ID ?? "",
    price: "$74.99/yr",
    priceValue: 74.99,
    billingPeriod: "yearly",
    plan: "basic",
    description: "Billed at 69% of monthly pricing.",
    creditAmount: 3000 * 12,
    songRetentionDays: null,
    priorityGeneration: false,
    reportCreditsIncluded: true,
    featured: false,
  },
  {
    name: "Pro Yearly",
    id: "pro_yearly",
    productId: process.env.CREEM_PRO_YEARLY_PRODUCT_ID ?? "",
    price: "$157.99/yr",
    priceValue: 157.99,
    billingPeriod: "yearly",
    plan: "pro",
    description: "Billed at 69% of monthly pricing.",
    creditAmount: 10000 * 12,
    songRetentionDays: null,
    priorityGeneration: true,
    reportCreditsIncluded: true,
    featured: true,
  },
];

export const ALL_TIERS = [...CREDIT_PACKS, ...SUBSCRIPTION_TIERS];

export function getTierById(id: string): ProductTier | undefined {
  return ALL_TIERS.find((tier) => tier.id === id);
}
