export const ERROR_CODES = {
  TIMEOUT: "TIMEOUT",
  PROVIDER_4XX: "PROVIDER_4XX",
  PROVIDER_5XX: "PROVIDER_5XX",
  BAD_RESPONSE: "BAD_RESPONSE",
  WEBHOOK_FAILED: "WEBHOOK_FAILED",
  CREDIT_OP_FAILED: "CREDIT_OP_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
